/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Source = IDL.Record({
  'url' : IDL.Text,
  'title' : IDL.Text,
  'excerpt' : IDL.Text,
});
export const Response = IDL.Record({
  'summarizedAnswer' : IDL.Text,
  'sources' : IDL.Vec(Source),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const QueryEntry = IDL.Record({
  'question' : IDL.Text,
  'response' : Response,
  'timestamp' : IDL.Int,
});
export const ExportConversation = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'lastUpdated' : IDL.Int,
  'entries' : IDL.Vec(QueryEntry),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const ExportData = IDL.Record({
  'conversations' : IDL.Vec(ExportConversation),
  'profile' : IDL.Opt(UserProfile),
});
export const ConversationSummary = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'lastUpdated' : IDL.Int,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addQueryEntry' : IDL.Func(
      [IDL.Nat, IDL.Text, Response, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createConversation' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'deleteConversationHistory' : IDL.Func([IDL.Nat], [], []),
  'exportUserData' : IDL.Func([], [ExportData], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getConversationEntries' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(QueryEntry)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listConversations' : IDL.Func([], [IDL.Vec(ConversationSummary)], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Source = IDL.Record({
    'url' : IDL.Text,
    'title' : IDL.Text,
    'excerpt' : IDL.Text,
  });
  const Response = IDL.Record({
    'summarizedAnswer' : IDL.Text,
    'sources' : IDL.Vec(Source),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const QueryEntry = IDL.Record({
    'question' : IDL.Text,
    'response' : Response,
    'timestamp' : IDL.Int,
  });
  const ExportConversation = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'lastUpdated' : IDL.Int,
    'entries' : IDL.Vec(QueryEntry),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const ExportData = IDL.Record({
    'conversations' : IDL.Vec(ExportConversation),
    'profile' : IDL.Opt(UserProfile),
  });
  const ConversationSummary = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'lastUpdated' : IDL.Int,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addQueryEntry' : IDL.Func(
        [IDL.Nat, IDL.Text, Response, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createConversation' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'deleteConversationHistory' : IDL.Func([IDL.Nat], [], []),
    'exportUserData' : IDL.Func([], [ExportData], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getConversationEntries' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(QueryEntry)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listConversations' : IDL.Func(
        [],
        [IDL.Vec(ConversationSummary)],
        ['query'],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };