/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Source = IDL.Record({
  'url' : IDL.Text,
  'title' : IDL.Text,
  'excerpt' : IDL.Text,
});
export const Response = IDL.Record({
  'summarizedAnswer' : IDL.Text,
  'sources' : IDL.Vec(Source),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const BlobRef = IDL.Record({ 'id' : IDL.Text, 'blob' : ExternalBlob });
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const QueryEntry = IDL.Record({
  'question' : IDL.Text,
  'response' : Response,
  'timestamp' : IDL.Int,
  'photo' : IDL.Opt(BlobRef),
});
export const ExportConversation = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'lastUpdated' : IDL.Int,
  'entries' : IDL.Vec(QueryEntry),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const ExportData = IDL.Record({
  'conversations' : IDL.Vec(ExportConversation),
  'profile' : IDL.Opt(UserProfile),
});
export const ConversationSummary = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'lastUpdated' : IDL.Int,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addQueryEntry' : IDL.Func(
      [IDL.Nat, IDL.Text, Response, IDL.Opt(IDL.Text), IDL.Opt(BlobRef)],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createConversation' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'deleteConversationHistory' : IDL.Func([IDL.Nat], [], []),
  'exportUserData' : IDL.Func([], [ExportData], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getConversationEntries' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(QueryEntry)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listConversations' : IDL.Func([], [IDL.Vec(ConversationSummary)], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Source = IDL.Record({
    'url' : IDL.Text,
    'title' : IDL.Text,
    'excerpt' : IDL.Text,
  });
  const Response = IDL.Record({
    'summarizedAnswer' : IDL.Text,
    'sources' : IDL.Vec(Source),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const BlobRef = IDL.Record({ 'id' : IDL.Text, 'blob' : ExternalBlob });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const QueryEntry = IDL.Record({
    'question' : IDL.Text,
    'response' : Response,
    'timestamp' : IDL.Int,
    'photo' : IDL.Opt(BlobRef),
  });
  const ExportConversation = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'lastUpdated' : IDL.Int,
    'entries' : IDL.Vec(QueryEntry),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const ExportData = IDL.Record({
    'conversations' : IDL.Vec(ExportConversation),
    'profile' : IDL.Opt(UserProfile),
  });
  const ConversationSummary = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'lastUpdated' : IDL.Int,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addQueryEntry' : IDL.Func(
        [IDL.Nat, IDL.Text, Response, IDL.Opt(IDL.Text), IDL.Opt(BlobRef)],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createConversation' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'deleteConversationHistory' : IDL.Func([IDL.Nat], [], []),
    'exportUserData' : IDL.Func([], [ExportData], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getConversationEntries' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(QueryEntry)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listConversations' : IDL.Func(
        [],
        [IDL.Vec(ConversationSummary)],
        ['query'],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };