/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BlobRef { 'id' : string, 'blob' : ExternalBlob }
export interface ConversationSummary {
  'id' : bigint,
  'title' : string,
  'lastUpdated' : bigint,
}
export interface ExportConversation {
  'id' : bigint,
  'title' : string,
  'lastUpdated' : bigint,
  'entries' : Array<QueryEntry>,
}
export interface ExportData {
  'conversations' : Array<ExportConversation>,
  'profile' : [] | [UserProfile],
}
export type ExternalBlob = Uint8Array;
export interface QueryEntry {
  'question' : string,
  'response' : Response,
  'timestamp' : bigint,
  'photo' : [] | [BlobRef],
}
export interface Response {
  'summarizedAnswer' : string,
  'sources' : Array<Source>,
}
export interface Source { 'url' : string, 'title' : string, 'excerpt' : string }
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addQueryEntry' : ActorMethod<
    [bigint, string, Response, [] | [string], [] | [BlobRef]],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createConversation' : ActorMethod<[string], bigint>,
  'deleteConversationHistory' : ActorMethod<[bigint], undefined>,
  'exportUserData' : ActorMethod<[], ExportData>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getConversationEntries' : ActorMethod<[bigint], Array<QueryEntry>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listConversations' : ActorMethod<[], Array<ConversationSummary>>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];